[package]
name = "bcder"
version = "0.2.1"
authors = ["The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>"]
description = "Handling of data encoded in BER, CER, and DER."
repository = "https://github.com/nlnetlabs/bcder"
keywords = ["ber", "cer", "der", "asn1", "decoding"]
categories = ["encoding", "network-programming", "parsing"]
license = "BSD-3-Clause"

[dependencies]
bytes       = "^0.4"
derive_more = "^0.14"

[features]
# Panic when a parsing error occurs. This feature is intended for
# development use exclusively and MUST NOT be enabled in release builds.
extra-debug = []
